### ISSUE TITLE
Manx UDP training tests for TCP

### ISSUE THREAD

**Issue by P0w3rChi3f** [mitre/manx#37]
**Describe the bug**
Going through the Caldera training and I got stuck on the "Manx UDP" test.  I was having issues getting the Manx terminal to connect to my UDP agent.  After some research and looking around I started noticing that the terminal only works with TCP.  I checked the caldera/plugins/training/app/flags/plugins/manx/flag_0.py and noticed it tested for TCP connection.  I was then able to pass the training. 

I am running Caldera 4.0.0 Beta on Ubuntu 20.04.1.  My UDP agent is running on Win10 21H1

**To Reproduce**
1. Deploy a Manx UDP agent
2. Attempt to run "whoami" or any command from the Manx terminal

**Expected behavior**
The test needs to reference TCP or the Manx terminal needs to be able to select a UDP beacon

**Screenshots**
Manx UDP Test (I believe line 20 is the issue)
<img width="1373" alt="Screen Shot 2022-03-10 at 8 11 17 PM" src="https://user-images.githubusercontent.com/21298973/157784712-69c4c6df-2028-41c8-98bf-8461e926ed31.png">

Screenshot of active UDP Connection
<img width="1406" alt="Screen Shot 2022-03-10 at 8 37 12 PM" src="https://user-images.githubusercontent.com/21298973/157785287-2440e920-26c5-404d-8a14-a4aa5f55b1fa.png">

Screenshot of no available beacon for the Manx terminal
<img width="808" alt="Screen Shot 2022-03-10 at 8 37 51 PM" src="https://user-images.githubusercontent.com/21298973/157785391-58bad8bd-5b0a-48f5-83e9-adb26af15346.png">

**Desktop (please complete the following information):**
 - OS: Caldera - Ubuntu 20.04, Agent - Win10 21H1, Operator Box - MacOS
 - Browser: Chrome
 - Version: Version 99.0.4844.51 (Official Build) (x86_64)

**Additional context**

**Comment by elegantmoose** [comment]
@P0w3rChi3f - Thanks for reporting. We added it to our sprint to look into.

**Comment by CDJellen** [comment]
Hello @P0w3rChi3f, thank you for the excellent and through issue submission.  The details, narrative, and screenshots you attached made pin-pointing this issue much more tenable.

**Comment by P0w3rChi3f** [comment]
You're Welcome.  I have not had time to re-download everything and try
again.  Hopefully, I will have time this weekend.

Thank you,

CW3 Jay Honeycutt
Cyber Operations Technician
ISSA Central Maryland VP of Outreach
Howard County Community College Adjunct Instructor
BSidesCharm Village Committee Lead

Cell:  501-339-6283
Website <http://www.jameshoneycutt.net>
Email ***@***.***>
LinkedIn <https://www.linkedin.com/in/james-honeycutt/>
*YouTube <https://www.youtube.com/channel/UCHKGcaCl8xAfXXcbkGe6D-g>*
***@***.***>
